spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2
---
### local ###
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
