spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
---
### local ###
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:~/test;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
## mockMvc 한글 깨짐 처리
server:
  servlet:
    encoding:
      force-response: true