spring:
  profiles:
    active: local

---
### local ###
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
## mockMvc 한글 깨짐 처리
server:
  servlet:
    encoding:
      force-response: true

---
### dev ###
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: # url
    username:   # user
    password:   # password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
